import pandas as pd
import numpy as np

data = pd.read_csv('Saber_11__2020-2.csv')

null_columns=data.columns[data.isnull().any()]
print(data[null_columns].isnull().sum())

nan = ["ESTU_GENERO", "ESTU_TIENEETNIA", "ESTU_DEPTO_RESIDE", "ESTU_COD_RESIDE_DEPTO", "ESTU_MCPIO_RESIDE", "ESTU_COD_RESIDE_MCPIO", "FAMI_ESTRATOVIVIENDA",
       "FAMI_PERSONASHOGAR", "FAMI_CUARTOSHOGAR", "FAMI_EDUCACIONPADRE", "FAMI_EDUCACIONMADRE" ,"FAMI_TRABAJOLABORPADRE" ,"FAMI_TRABAJOLABORMADRE" ,
       "FAMI_TIENEINTERNET" ,"FAMI_TIENESERVICIOTV" ,"FAMI_TIENECOMPUTADOR" ,"FAMI_TIENELAVADORA" ,"FAMI_TIENEHORNOMICROOGAS" ,"FAMI_TIENEAUTOMOVIL" ,
       "FAMI_TIENEMOTOCICLETA" ,"FAMI_TIENECONSOLAVIDEOJUEGOS" ,"FAMI_NUMLIBROS" ,"FAMI_COMELECHEDERIVADOS" ,"FAMI_COMECARNEPESCADOHUEVO" ,"FAMI_COMECEREALFRUTOSLEGUMBRE" ,
       "FAMI_SITUACIONECONOMICA" ,"ESTU_DEDICACIONLECTURADIARIA" ,"ESTU_DEDICACIONINTERNET" ,"ESTU_HORASSEMANATRABAJA" ,"ESTU_TIPOREMUNERACION" ,"COLE_BILINGUE" ,
       "COLE_CARACTER" ,"ESTU_COD_MCPIO_PRESENTACION" ,"ESTU_MCPIO_PRESENTACION" ,"ESTU_DEPTO_PRESENTACION" ,"ESTU_COD_DEPTO_PRESENTACION" ,"PUNT_INGLES" ,
       "ESTU_INSE_INDIVIDUAL" ,"ESTU_NSE_INDIVIDUAL" ,"ESTU_NSE_ESTABLECIMIENTO"]

for i in range(0, 800000):
  if data[data["COLE_CODIGO_ICFES"] == i].shape[0] > 0:
    print(i)
    if data[data["COLE_CODIGO_ICFES"] == i].isnull().any().shape[0] > 0:

        for j in nan:
          mode = data.loc[data["COLE_CODIGO_ICFES"] == i,j].mode()
          if mode.isnull:
            mode = data[j].mode()
          data.loc[data["COLE_CODIGO_ICFES"] == i,j] = data.loc[data["COLE_CODIGO_ICFES"] == i,j].fillna(mode[0])

data.to_csv('withoutnil.csv')